#server:
#  port: 3000

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${JDBC_URL}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:w&%9#Pcd37}

  jpa:
    hibernate:
      ddl-auto: create-drop # PARO A APLICAÇÃO, O BANCO É DESTRUÍDO. SUBO A APLICAÇÃO, O BANCO É CRIADO DO ZERO
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect